[package]
name = "embedded-multi-page-hmi"
version = "0.1.0"
edition = "2018"
license = "MIT"


[dependencies]

[dev-dependencies]
chrono = "0.4.19"

[target.'cfg(unix)'.dev-dependencies]
termios = "0.3.3"
