name: Publish

# Only publish tagged commits of certain branches
#
# Policy is:
# - trunk based development
#   - i.e. only master gets pushed
#   - other branches are for CI qualification prior to rebasing to master
# - tags are only created with cargo bump -g <major|minor|patch> -> so any tags get pushed
on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
